# Python 3.9 Slim 이미지를 기반으로 사용
FROM python:3.9-slim

# 컨테이너 내부의 작업 디렉토리 설정
WORKDIR /app

# 로컬 디렉토리의 모든 파일을 컨테이너로 복사
COPY . .

# 필요한 Python 패키지 설치
RUN pip install --no-cache-dir Flask flask_sqlalchemy pymysql

# Flask 애플리케이션이 사용하는 포트 열기
EXPOSE 3309

# Flask 애플리케이션 실행
ENTRYPOINT ["python", "ai_test.py"]